### ISSUE TITLE
assocLMer

### ISSUE THREAD

**Issue by tshori** [variani/lme4qtl#14]
Dear Dr. Ziyatdinov,

I am trying to use the assoCLmer function to analyse my data (it's a fish, I have 46K SNPs and about 6000 individuals), but I am having trouble figuring out from the function how the trait ans SNP data should be formatted for input. If I am reading the function correctly, this is a 2-step approach, It first fist a model without the SNPs (and I assume it used a relationship matrix G generated from the SNP data) and the fits one SNP at time. Is that correct? 
Lastly, I was wondering if it is possible to extract r-squared for the individual SNP test,

Sorry for all the questions.

Cheers,

Tiago

**Comment by variani** [comment]
Hi Tiago,

Thanks for posting this GWAS question.

[assocLmer](https://github.com/variani/lme4qtl/blob/master/R/relmatAssoc.R#L6) was initially designed as an example function (as mentioned in our [article](http://dx.doi.org/10.1186/s12859-018-2057-x)), because association studies are different in many practical aspects from my experience:

- the SNP data format the function needs to support;
- the SNP data might be rather big and some tricks are needed; 
- handling missing SNP data and other QC;
- statistical tests and computation, e.g. two-step approach you mention.

I would suggest you to write your own R code using some lme4qtl functions like relmatLmer/varcov. I also create a small [demo](https://github.com/variani/lme4qtl/blob/master/demo/gwas.R) for my colleges asking a similar question on how to do GWAS.

I don't have any specific comments on assocLmer implementation. I assume it should be clear to a person like me who run GWAS using `lm` methods and has some experience with lme4. I believe R users can do a better job than me!

**Comment by tshori** [comment]
Thanks!

I am working on it. I will update the thread if I get something to work.

Cheers,

Tiago
